[package]
name = "pennbauman_com"
version = "0.2.0"
authors = ["Penn Bauman <me@pennbauman.com>"]
edition = "2018"

[dependencies]
tide = "0.15.0"
async-std = { version = "1.6.0", features = ["attributes"] }
tera = "1.6.0"
tide-tera = "0.2.3"

[build-dependencies]
sass-rs = "0.2"
